package ren.oliver.mybatis.spring.mapper;

import java.util.List;
import ren.oliver.mybatis.spring.entity.THealthReportFemale;

public interface THealthReportFemaleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_health_report_female
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_health_report_female
     *
     * @mbggenerated
     */
    int insert(THealthReportFemale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_health_report_female
     *
     * @mbggenerated
     */
    THealthReportFemale selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_health_report_female
     *
     * @mbggenerated
     */
    List<THealthReportFemale> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_health_report_female
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(THealthReportFemale record);
}